// THIS FILE HAS NO. OF ACTION CREATOR FUNCTION WHICH DISPATCH ACTIONS. 
// THIS ACTION THEN HIT EACH REDUCER AND UPDATE THE STATE TARGETING THE APPROPRIATE REDUCERS ACTION TYPES

// ACTION CREATOR TAKES DISPATCH AS A ARGUMENT 

