import {useEffect,useState} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Header,Footer} from '../components';
// import {firebaseApp} from '../firebase'
// import { getAuth, GoogleAuthProvider, signInWithPopup,signInWithPhoneNumber,FacebookAuthProvider } from "firebase/auth";



function Home({user}) {
  
  // const auth = getAuth(firebaseApp);
  // const [user,setUser] = useState(null);

  // useEffect(()=>{
  //   const removeOnStateChangeListener = auth.onAuthStateChanged(()=>{
  //     const currUser = auth.currentUser;
  //     if(!currUser)
  //       return setUser(null);
        
  //       setUser({name:currUser?.displayName,email:currUser?.email});
  //   })

  //   return ()=>{
  //     removeOnStateChangeListener();
  //   }

  // },[]); 

  return (
    <div  className='bg-gradient-to-tr from-slate-900 to-slate-800' >
      <Head>
        <title>MedHistory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main >
      <Header user = {user} bgshow={false} />
        <div className='flex  space-x-8 pt-8 mx-8  rounded-lg items-center '>
          <img className='object-contain'  onContextMenu={(e)=>e.preventDefault()} onDragStart={(e)=>e.preventDefault()}  src = "https://img.smartspends.com/static/images/etmoneyweb/insurance/health-banner.png"/>
          <h1 className=' top-1/3 right-[50px] text-indigo-100 text-3xl font-semibold w-[400px]'>Now keep your medical prescription safe, secure and easily accessible</h1>
          {/* <button>Click here</button> */}
        </div>

      <div className='flex justify-between  m-8 mx-[5%] rounded-xl shadow-md bg-gradient-to-tr from-indigo-800 to-slate-800'>

        <div className='flex flex-col items-center flex-1 justify-center'>
            <h1 className='font-semibold text-3xl p-4 text-indigo-100'>Get prescribed online</h1>
            <button className='rounded-full bg-white text-gray-500 px-4 py-1 text-lg font-semibold shadow-md  transition active:scale-95 hover:text-blue-400 duration-100'>Explore More</button>
        </div>
        <div className='relative h-64 w-80'>
            <Image
                layout='fill'
                src="https://pngimg.com/uploads/doctor/doctor_PNG15964.png"
                onContextMenu={(e)=>e.preventDefault()} 
                onDragStart={(e)=>e.preventDefault()} 
              />
        </div>
       
      
      </div>


          {/* family section */}

        <div className='flex m-8  mx-[5%] rounded-xl shadow-md space-x-5 items-center  bg-gradient-to-tr from-indigo-800 to-slate-800'>
          <div className='relative h-[450px] w-[550px]'>
              <Image className='rounded-md'  onContextMenu={(e)=>e.preventDefault()} onDragStart={(e)=>e.preventDefault()} layout='fill' src="/family.png"/>
          </div>
       
          <h1 className='text-indigo-100 text-3xl font-semibold'>
            View your medical history to the people you trust
          </h1>
        </div>
      
      <div className='flex justify-between m-8  mx-[5%] rounded-xl shadow-md  bg-gradient-to-tr from-indigo-800 to-slate-800'>

        <div className=' flex flex-col items-center flex-1 justify-center'>
            <h1 className='font-bold text-xl p-4 text-indigo-100'>Get prescribed by local doctors and access digital medical history </h1>
            <button className='rounded-full bg-white text-gray-500 px-4 py-1 text-lg font-semibold shadow-md  transition active:scale-95 hover:text-blue-400 duration-100'>Explore More</button>
        </div>
        <div className='relative h-64 w-80'>
          <Image  layout='fill' className = "rounded-md" onContextMenu={(e)=>e.preventDefault()} onDragStart={(e)=>e.preventDefault()} src="/docImage.png" />

        </div>
      
      </div>




    </main>
    <footer className=''>
      <Footer/>
    </footer>
    </div>
  )
}



export default Home;