import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';

export default function Home() {
  return (
    <div  className=''>
      <Head>
        <title>MedHistory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main >
      <Header/>
      <div className='relative flex justify-between m-8 rounded-lg items-center '>
        <img className='object-contain' src = "https://img.smartspends.com/static/images/etmoneyweb/insurance/health-banner.png"/>
        <h1 className=' top-1/3 right-[50px] text-gray-600 text-2xl font-semibold w-[400px]'>Now keep your medical prescription safe, secure and easily accessible</h1>
        <button></button>

      </div>

      <div className='flex justify-between m-8 rounded-md shadow-md bg-gray-100'>

        <div className='flex flex-col items-center flex-1 justify-center'>
            <h1 className='font-bold text-xl p-4 text-gray-800'>Get prescribed online</h1>
            <button className='rounded-full bg-white text-gray-500 px-4 py-1 text-lg font-semibold shadow-md  transition active:scale-95 hover:text-blue-400 duration-100'>Explore More</button>
        </div>
        <img className='h-[220px]' src="https://www.nicepng.com/png/detail/26-260551_femscare-benifits-doctor-image-png-hd.png" />
      
      </div>


          {/* family section */}

        <div className='flex m-8 rounded-xl shadow-md bg-gray-800 items-center space-x-5'>
          <img className='object-scale-down w-full h-80' src="https://media.istockphoto.com/photos/happy-multiethnic-family-mom-dad-and-child-laughing-playing-and-on-picture-id1282222916?b=1&k=20&m=1282222916&s=170667a&w=0&h=bRdap7obX6sxxo4j3UalSrwtt4oLk5H4U8ppYmyBoQo="/>
          {/* <h1 className='text-white text-2xl '>
            View medical history of your family members, friends or your trust worthy
          </h1> */}
        </div>
      
      <div className='flex justify-between m-8 rounded-md shadow-md bg-gray-100'>

        <div className='flex flex-col items-center flex-1 justify-center'>
            <h1 className='font-bold text-xl p-4 text-gray-800'>Get prescribed by local doctors and access digital medical history </h1>
            <button className='rounded-full bg-white text-gray-500 px-4 py-1 text-lg font-semibold shadow-md  transition active:scale-95 hover:text-blue-400 duration-100'>Explore More</button>
        </div>
        <img className='h-[220px]' src="https://images.unsplash.com/photo-1613918108466-292b78a8ef95?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80" />
      
      </div>




    </main>
    <footer className='shadow-md bg-yellow-200'>
      Know more about us
    </footer>
    </div>
  )
}
